server:
    port: 8080
# datasoucre
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.96.32.255:3306/sina?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: Zp688420!
    initialSize: 20
    minIdle: 10
    maxActive: 100
  thymeleaf:
      prefix: classpath:/templates/
      check-template-location: true
      suffix: .html
      encoding: UTF-8
      mode: HTML5
      cache: false

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      news:
        sina:
          dao: debug
# spring.thymeleaf.content-type: text/html
